# Generated by Django 4.0.4 on 2022-04-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco_origem', models.CharField(max_length=20)),
                ('agencia_origem', models.CharField(max_length=20)),
                ('conta_origem', models.CharField(max_length=20)),
                ('banco_destino', models.CharField(max_length=20)),
                ('agencia_destino', models.CharField(max_length=20)),
                ('conta_destino', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
            ],
        ),
    ]
