# Generated by Django 4.0.4 on 2022-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_import',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_transactions',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='valor',
            field=models.FloatField(),
        ),
    ]
