# Generated by Django 4.0.4 on 2022-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_history_date_import_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='banco_destino',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='banco_origem',
            field=models.CharField(max_length=50),
        ),
    ]
