# Generated by Django 4.0.4 on 2022-04-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_transactions_banco_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
