# Generated by Django 4.0.4 on 2022-04-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date_transactions',
            field=models.CharField(default='01-01-2022', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='date_transactions',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
